### ISSUE TITLE
last throws an exception on some lists.

### ISSUE THREAD

**Issue by EleanorWhite** [cartazio/ralist#2]
When you run the command:

> last (fromList [1,2,3,4,5,6,7,8,9]) 
> it gives back the error:
> '''
> **\* Exception: Data.RAList.!!: impossible
> CallStack (from HasCallStack):
>   error, called at RAList.hs:344:18 in main:Data.RAList
> '''

This, I think, is caused by a problem with the !! function, which breaks when it is given an RAList of length nine and the indices 1, 7, and 8.

**Comment by cartazio** [comment]
Woah! Excellent catch :)

**Comment by cartazio** [comment]
looks like the issue was a similar bug as adjust, i've a fix i'm about to push to master

**Comment by cartazio** [comment]
(and yes, the bug was in !!, which kept on using the index/size `n` in the recursion rather than the correct one, `j`)
