### ISSUE TITLE
notElem returns True unless every element in the list is the value being checked

### ISSUE THREAD

**Issue by EleanorWhite** [cartazio/ralist#3]
notElem returns True when it is given an  RAList with the value it is checking for along with other values:

```
> notElem 1 (fromList [1,2])
True
```

It works correctly as long as the list contains only one value:

```
> notElem 1 (fromList [1,1])
False
```

.

**Comment by cartazio** [comment]
ok, we have some work to do!

again, great job! (seriously thanks).

I'll have some time to start digging into this this coming weekend/next
week.

would you like to skype coord / collaborate on this? I really really
appreciate this stuff.

**Comment by EleanorWhite** [comment]
Thanks!

Also I'd be down to coord/collaborate.

**Comment by cotrone** [comment]
It looks like https://github.com/cartazio/ralist/blob/master/Data/RAList.hs#L486 is defined incorrectly. notElem should probably just be not . elem. any (/= x) doesn't make sense for checking if an element isn't in a list.

**Comment by cartazio** [comment]
@EleanorWhite  got a bit side tracked, i'm doing a quick fix on all these for now/today, but lets try to figure out chatting this coming weekend? shoot me an email and lets coord!

**Comment by cartazio** [comment]
fixed, but coord point still stands :)
