### ISSUE TITLE
Update and adjust break on some inputs

### ISSUE THREAD

**Issue by EleanorWhite** [cartazio/ralist#4]
These functions will sometimes skip indices.
Generally they will work fine for the first value:

```
> update 0 0 (fromList [1..5])
[0,2,3,4,5]
```

But after that they will sometimes skip over values and move all subsequent updates to the right by one:

```
> update 1 0 (fromList [1..5])
[1,2,0,4,5]
> update 2 0 (fromList [1..5])
[1,2,3,0,5]
> update 3 0 (fromList [1..5])
fromList [1,2,3,4,5** Exception: Data.RAList.adjust: impossible
CallStack (from HasCallStack):
  error, called at RAList.hs:540:19 in main.Data.RAList
```

I believe the command to update at index 3 threw an error because it also skipped the last value in the list which made it think three was out of bounds.

**Comment by cartazio** [comment]
This bug and others : 😭😱

You taking the time to find and report them: ✨🎉👋🕵😎👍

If you feel comfortable having a go at fixing one , PR welcome.  Else let's
synch up end of this weekend early next week after I've some time to poke
at stuff myself

**Comment by cartazio** [comment]
this should be fixed in master now :)
